#!/usr/bin/env python3
import json
import multiprocessing as mp
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import language_tool_python


BASE_DIR: Path = Path(__file__).resolve().parent
MIN_WORDS_PER_BLOCK: int = 30
MAX_WORDS_PER_BLOCK: int = 90
MAX_PROCESSES: int = 3
TIMESTAMP_PATTERN: re.Pattern[str] = re.compile(
  r"^\[(\d{2}:\d{2}:\d{2}\.\d{3})\s+-->\s+(\d{2}:\d{2}:\d{2}\.\d{3})\]$"
)
TOOL: language_tool_python.LanguageTool | None = None


@dataclass
class TranscriptSegment:
  """Represent one timestamped transcription segment."""

  timestamp: str
  start_time: str
  end_time: str
  text: str
  is_music: bool


def is_music_text(text: str) -> bool:
  """Return whether the segment is an allowed music marker."""
  normalized: str = text.strip()
  return normalized in {"[MÚSICA]", "[Música]"}


def find_transcription_files(base_dir: Path) -> list[Path]:
  """Find every transcription JSON generated by the previous step."""
  transcription_files: list[Path] = []
  for pipeline_dir in sorted(base_dir.glob("pipeline_*")):
    if not pipeline_dir.is_dir():
      continue
    for json_file in sorted(pipeline_dir.glob("*_transcription.json")):
      transcription_files.append(json_file)
  return transcription_files


def parse_timestamp(timestamp: str) -> tuple[str, str]:
  """Extract start and end time from a timestamp key."""
  match: re.Match[str] | None = TIMESTAMP_PATTERN.match(timestamp.strip())
  if match is None:
    raise ValueError(f"Invalid timestamp format: {timestamp}")
  return match.group(1), match.group(2)


def clean_ellipsis_edges(text: str) -> str:
  """Remove leading and trailing ellipsis and unnecessary commas."""
  cleaned_text: str = text.strip()
  cleaned_text = re.sub(r"^\s*,?\s*(?:\.\s*){2,}\s*,?\s*", "", cleaned_text)
  cleaned_text = re.sub(r"\s*,?\s*(?:\.\s*){2,}\s*,?\s*$", "", cleaned_text)
  cleaned_text = re.sub(r"^\s*,+\s*", "", cleaned_text)
  cleaned_text = re.sub(r"\s*,+\s*$", "", cleaned_text)
  cleaned_text = re.sub(r"\s+", " ", cleaned_text).strip()
  return cleaned_text


def clean_speech_text(text: str) -> str:
  """Apply character filtering and bracket cleanup to speech text."""
  without_brackets: str = re.sub(r"\[[^\]]*\]", " ", text)
  filtered_chars: list[str] = []
  for character in without_brackets:
    if character.isalnum() or character in {".", ",", " "}:
      filtered_chars.append(character)

  filtered_text: str = "".join(filtered_chars)
  filtered_text = re.sub(r"\s+", " ", filtered_text).strip()
  return clean_ellipsis_edges(filtered_text)


def count_words(text: str) -> int:
  """Count words using whitespace tokenization."""
  if not text.strip():
    return 0
  return len(text.split())


def load_segments(transcription_map: dict[str, Any], tool: language_tool_python.LanguageTool) -> list[TranscriptSegment]:
  """Load ordered transcript segments from the transcription mapping."""
  segments: list[TranscriptSegment] = []
  for timestamp, raw_text in transcription_map.items():
    if not isinstance(timestamp, str):
      raise ValueError("Transcription timestamp keys must be strings")
    if not isinstance(raw_text, str):
      raise ValueError(f"Transcription value for {timestamp} must be a string")

    start_time, end_time = parse_timestamp(timestamp)
    text: str = raw_text.strip()
    text = tool.correct(text)
    segments.append(
      TranscriptSegment(
        timestamp=timestamp,
        start_time=start_time,
        end_time=end_time,
        text=text,
        is_music=is_music_text(text),
      )
    )
  return segments


def clean_and_dedupe_segments(segments: list[TranscriptSegment]) -> list[TranscriptSegment]:
  """Clean transcript text and remove consecutive duplicate speech entries."""
  cleaned_segments: list[TranscriptSegment] = []
  previous_speech_text: str | None = None

  for segment in segments:
    if segment.is_music:
      cleaned_segments.append(segment)
      previous_speech_text = None
      continue

    cleaned_text: str = clean_speech_text(segment.text)
    if not cleaned_text:
      continue
    if previous_speech_text == cleaned_text:
      continue

    cleaned_segment: TranscriptSegment = TranscriptSegment(
      timestamp=segment.timestamp,
      start_time=segment.start_time,
      end_time=segment.end_time,
      text=cleaned_text,
      is_music=False,
    )
    cleaned_segments.append(cleaned_segment)
    previous_speech_text = cleaned_text

  return cleaned_segments


def merge_speech_segments(segments: list[TranscriptSegment]) -> dict[str, str]:
  """Merge speech segments into 30-90 word blocks while preserving music."""
  merged_transcription: dict[str, str] = {}
  block_start: str | None = None
  block_end: str | None = None
  block_texts: list[str] = []
  block_words: int = 0

  def flush_block() -> None:
    """Write the current speech block to the merged mapping."""
    nonlocal block_start
    nonlocal block_end
    nonlocal block_texts
    nonlocal block_words

    if block_start is None or block_end is None or not block_texts:
      return

    merged_text: str = " ".join(block_texts).strip()
    if merged_text:
      merged_timestamp: str = f"[{block_start} --> {block_end}]"
      merged_transcription[merged_timestamp] = merged_text

    block_start = None
    block_end = None
    block_texts = []
    block_words = 0

  for segment in segments:
    if segment.is_music:
      flush_block()
      merged_transcription[segment.timestamp] = segment.text
      continue

    segment_words: int = count_words(segment.text)
    if segment_words == 0:
      continue

    if block_start is None:
      block_start = segment.start_time
      block_end = segment.end_time
      block_texts = [segment.text]
      block_words = segment_words
      continue

    if block_words + segment_words > MAX_WORDS_PER_BLOCK:
      flush_block()
      block_start = segment.start_time
      block_end = segment.end_time
      block_texts = [segment.text]
      block_words = segment_words
      continue

    block_texts.append(segment.text)
    block_end = segment.end_time
    block_words += segment_words

    if block_words >= MIN_WORDS_PER_BLOCK:
      flush_block()

  flush_block()
  return merged_transcription


def output_path_for(input_path: Path) -> Path:
  """Build the output path with the _merged suffix."""
  return input_path.with_name(f"{input_path.stem}_merged.json")


def init_worker() -> None:
  """Load shared worker resources once per worker process."""
  global TOOL
  TOOL = language_tool_python.LanguageTool("es-ES")


def process_transcription_file(file_path: Path) -> Path:
  """Process one transcription file and write the merged output JSON."""
  if TOOL is None:
    raise RuntimeError("Worker language tool is not initialized.")

  data: Any = json.loads(file_path.read_text(encoding="utf-8"))
  if not isinstance(data, dict):
    raise ValueError(f"Invalid JSON structure in {file_path}")

  raw_transcription: Any = data.get("transcription")
  if not isinstance(raw_transcription, dict):
    raise ValueError(f"Missing or invalid 'transcription' in {file_path}")

  segments: list[TranscriptSegment] = load_segments(raw_transcription, TOOL)
  cleaned_segments: list[TranscriptSegment] = clean_and_dedupe_segments(segments)
  merged_transcription: dict[str, str] = merge_speech_segments(cleaned_segments)

  output_data: dict[str, Any] = dict(data)
  output_data["transcription"] = merged_transcription

  merged_path: Path = output_path_for(file_path)
  merged_path.write_text(
    json.dumps(output_data, ensure_ascii=False, indent=2),
    encoding="utf-8",
  )
  return merged_path


def main() -> None:
  """Process all pipeline transcription files and write merged outputs."""
  transcription_files: list[Path] = find_transcription_files(BASE_DIR)
  if not transcription_files:
    print("No transcription files found in pipeline folders.")
    return

  with mp.Pool(processes=MAX_PROCESSES, initializer=init_worker) as pool:
    merged_files: list[Path] = pool.map(process_transcription_file, transcription_files)

  for merged_file in merged_files:
    print(f"Saved merged transcription: {merged_file}")


if __name__ == "__main__":
  main()
